FROM node:lts as builder
WORKDIR /src/
COPY webui webui
COPY nginx.conf nginx.conf
COPY nginx.conf /etc/nginx/nginx.conf
WORKDIR /src/webui
RUN npm run build-prod

FROM nginx:stable-alpine
COPY --from=builder /src/webui/dist /usr/share/nginx/html
CMD [ "nginx", "-g", "daemon off;" ]